import type { Metadata } from "next";
import { Roboto } from "next/font/google";

import Navbar from "@/components/Navbar";

import "./globals.css";

// Import font
const robotoSerif = Roboto({
  variable: "--font-roboto-serif",
  subsets: ["latin"],
});

// Set meta data
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// The Layout
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Returned JSX
  return (
    <html lang="en">
      <body className={`${robotoSerif.className}`}>
        <Navbar />
        <main className="max-w-3xl mx-auto py-1">{children}</main>
      </body>
    </html>
  );
}
